# Generated by Django 4.2.7 on 2023-11-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary'), ('P', 'Prefer Not to Say')], max_length=1)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('medical_history', models.TextField(max_length=250)),
                ('update_date', models.DateField(verbose_name='Update date')),
            ],
        ),
    ]
