# Generated by Django 4.2.7 on 2023-11-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Visit date')),
                ('visit_type', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('treatment', models.TextField(max_length=250)),
                ('follow_up', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.member')),
            ],
        ),
    ]
