# Generated by Django 4.2.7 on 2023-11-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
