# Generated by Django 4.2.7 on 2023-11-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_appointment_follow_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='treatment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
